Repository okta/okta-developer-docs, pull requests merged in 2020-09, with the labels that each got.

#1360 Add production deployment guide
  packages/@okta/vuepress-site/docs/guides/production-deployment/index.md
Labels: cdg_v1

#1436 Approved by security (#1435)
  packages/@okta/vuepress-site/docs/release-notes/2020-09-1/index.md
Labels: docs release

#1439 Fix the Okta Sign-In Widget and Angular guide
  packages/@okta/vuepress-site/.vuepress/nav/codePages.js
  packages/@okta/vuepress-site/books/api-security/sanitizing/common-attacks/index.md
  packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
  packages/@okta/vuepress-site/docs/concepts/authentication/index.md
  packages/@okta/vuepress-site/docs/reference/api/authn/index.md
  packages/@okta/vuepress-site/docs/reference/api/factors/index.md
  packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
  packages/@okta/vuepress-site/docs/release-notes/2017-27/index.md
Labels: cdg_v1

#1375 CDG QuickStart
  packages/@okta/vuepress-site/.vuepress/nav/guides.js
  packages/@okta/vuepress-site/.vuepress/scripts/build-guides-info.js
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/add-user/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/create-org/cli/create-org.md
  packages/@okta/vuepress-site/docs/guides/quickstart/create-org/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/create-org/website/create-org.md
  packages/@okta/vuepress-site/docs/guides/quickstart/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/register-app/cli/register-app.md
  packages/@okta/vuepress-site/docs/guides/quickstart/register-app/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/register-app/website/register-app.md
  packages/@okta/vuepress-site/docs/guides/quickstart/sign-in/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/try-api/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/try-api/java/try-api.md
  packages/@okta/vuepress-site/docs/guides/quickstart/using-console/index.md
Labels: cdg_v1

#1372 styling the widget
  packages/@okta/vuepress-site/.vuepress/nav/guides.js
  packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/okta-hosted-flows/index.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/use-idp-to-sign-in/index.md
  packages/@okta/vuepress-site/docs/guides/custom-error-pages/next-steps/index.md
  packages/@okta/vuepress-site/docs/guides/custom-error-pages/overview/index.md
  packages/@okta/vuepress-site/docs/guides/custom-hosted-signin/edit-the-sign-in-page/index.md
  packages/@okta/vuepress-site/docs/guides/custom-hosted-signin/index.md
  packages/@okta/vuepress-site/docs/guides/custom-hosted-signin/next-steps/index.md
  packages/@okta/vuepress-site/docs/guides/custom-hosted-signin/overview/index.md
  packages/@okta/vuepress-site/docs/guides/custom-hosted-signin/use-macros-and-request-context/index.md
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/next-steps/index.md
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/overview/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/next-steps/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/next-steps/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/sign-in-page/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa/add-signin-button/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa/next-steps/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-web-app/next-steps/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-web-app/redirect-to-sign-in/index.md
  packages/@okta/vuepress-site/docs/guides/sign-users-out/next-steps/index.md
  packages/@okta/vuepress-site/docs/guides/style-the-widget/before-you-begin/index.md
  packages/@okta/vuepress-site/docs/guides/style-the-widget/customization-examples/index.md
  packages/@okta/vuepress-site/docs/guides/style-the-widget/index.md
  packages/@okta/vuepress-site/docs/guides/style-the-widget/next-steps/index.md
  packages/@okta/vuepress-site/docs/guides/style-the-widget/style-okta-hosted/index.md
  packages/@okta/vuepress-site/docs/guides/style-the-widget/style-self-hosted/index.md
  packages/@okta/vuepress-site/docs/reference/api/authn/index.md
  packages/@okta/vuepress-site/docs/release-notes/2018-19/index.md
Labels: cdg_v1

#1455 CDG QuickStart
  packages/@okta/vuepress-site/.vuepress/nav/guides.js
  packages/@okta/vuepress-site/.vuepress/scripts/build-guides-info.js
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/add-user/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/create-org/cli/create-org.md
  packages/@okta/vuepress-site/docs/guides/quickstart/create-org/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/create-org/website/create-org.md
  packages/@okta/vuepress-site/docs/guides/quickstart/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/register-app/cli/register-app.md
  packages/@okta/vuepress-site/docs/guides/quickstart/register-app/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/register-app/website/register-app.md
  packages/@okta/vuepress-site/docs/guides/quickstart/sign-in/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/try-api/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/using-console/index.md
  packages/@okta/vuepress-theme-prose/util/frameworks.js
Labels: cdg_v1

#1473 QuickStart: Change recommended redirect URI for consistency
  packages/@okta/vuepress-site/docs/guides/quickstart/register-app/cli/register-app.md
  packages/@okta/vuepress-site/docs/guides/quickstart/register-app/website/register-app.md
  packages/@okta/vuepress-site/docs/guides/quickstart/try-api/index.md
  packages/@okta/vuepress-site/docs/guides/quickstart/using-console/index.md
Labels: cdg_v1

#1464 Add How to Deploy Guide
  packages/@okta/vuepress-site/.vuepress/nav/guides.js
  packages/@okta/vuepress-site/docs/guides/deploy-your-app/index.md
  packages/@okta/vuepress-site/docs/guides/deploy-your-app/java/index.md
  packages/@okta/vuepress-site/docs/guides/deploy-your-app/javascript/index.md
  packages/@okta/vuepress-site/docs/guides/deploy-your-app/mobile/index.md
  packages/@okta/vuepress-site/docs/guides/deploy-your-app/overview/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
Labels: cdg_v1

#1470 API Release Notes - 2020.09.3
  packages/@okta/vuepress-site/docs/release-notes/2020-09-3/index.md
Labels: docs release

#1381 Bugfixes for At This Page Mobile components
  packages/@okta/vuepress-theme-prose/assets/css/components/_onThisPage.scss
  packages/@okta/vuepress-theme-prose/components/MobileOnThisPage.vue
Labels: Vuepress

#1481 /docs navbar fixed and identical to rest of the site
  packages/@okta/vuepress-theme-prose/assets/css/components/_search.scss
  packages/@okta/vuepress-theme-prose/assets/css/components/_top-bar.scss
  packages/@okta/vuepress-theme-prose/assets/css/layouts/_layout.scss
  packages/@okta/vuepress-theme-prose/components/TopBar.vue
Labels: Vuepress
