Repository okta/okta-developer-docs, pull requests merged in 2021-06, with the labels that each got.

#2157 Added device condition to signon policy API in the dev doc
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
Labels: Identity Engine

#2167 Adding content for the new flexible consent option
  packages/@okta/vuepress-site/docs/guides/request-user-consent/overview/index.md
  packages/@okta/vuepress-site/docs/guides/request-user-consent/require-consent/index.md
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
  packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md
  packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
Labels: docs release

#2127 sda-OKTA-394895 Update List Applications API Doc
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Labels: docs release

#2182 removing the EA flags
  packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md
  packages/@okta/vuepress-site/docs/guides/refresh-tokens/refresh-token-rotation/index.md
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
  packages/@okta/vuepress-theme-prose/components/Pricing.vue
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
  yarn.lock
Labels: docs release

#2195 OKTA-375130 Redirect vs Embedded Authentication OIE Concept
  packages/@okta/vuepress-site/.vuepress/public/img/embedded-auth-seq-flow.png
  packages/@okta/vuepress-site/.vuepress/public/img/redirect-auth-seq-flow.png
  packages/@okta/vuepress-site/docs/concepts/redirect-vs-embedded/index.md
Labels: Identity Engine

#2213 gborah-OKTA-402993 add PROFILE_ENROLLMENT and ACCESS_POLICY in Policy Object table
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
Labels: Identity Engine

#2199 VN OKTA 399045 OIE SDKs and Samples page
  packages/@okta/vuepress-site/code/oie/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Identity Engine

#2227 intro update per Emeka and Daniel Lu
  packages/@okta/vuepress-site/docs/concepts/ie-intro/index.md
Labels: Work In Process

#2165 Add OIE rate limits
  packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
  packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
Labels: Identity Engine

#2279 Add OIE Endpoints to Dynamic Scale and Workforce
  packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
  packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
Labels: Identity Engine

#2287 Rn entry 2021.06.4
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
Labels: docs release
