Repository okta/okta-developer-docs, pull requests merged in 2022-04, with the labels that each got.

#3118 [OKTA-459397] Okta Verify (Push/OTP) integration guide (.NET SDK)
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-challenge-enter-totp.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-challenge-list-of-authenticators.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-challenge-list-of-challenge-methods.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-challenge-push-sent.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-challenge-with-push.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-challenge-with-totp.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-enrol-with-QRcode.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-enrol-with-email.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-enrollment-email-prompt-for-address.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-enrollment-email-prompt-user-to-check-email.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-enrollment-email-text.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-enrollment-list-of-authenticators.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-enrollment-list-of-other-enrollment-options.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-enrollment-scan-qr-code.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-shared-code-initiate-signin.png
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators/dotnet-authenticators-okta-verify-shared-code-polling.png
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/challengepushintegrationsteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/challengepushintegrationsummary.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/challengetotpintegrationsteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/challengetotpintegrationsummary.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/commonsteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/enrollmentotherintegrationsteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/enrollmentotherintegrationsummary.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/enrollmentqrcodeintegrationsteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/enrollmentqrcodeintegrationsummary.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/orgconfigurepwdonly.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/relatedusecases.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/samplecode.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/whatyouneedorg.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/aspnet/whatyouneedsdk.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/nodeexpress/enrollmentotherintegrationsummary.md
Labels: guides, Identity Engine, final review complete

#3206 [OKTA-459221] Authenticators contextual landing page
  packages/@okta/vuepress-site/docs/guides/authenticators-overview/main/index.md
Labels: guides, Identity Engine, final edit ready

#3173 Adding initial draft of Angular and Auth JS SDK guide
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/basic-sign-in.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/download-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/intro.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/next-steps.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/see-also.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/sign-in-form.md
Labels: Identity Engine, final review complete

#3258 TBS OKTA-453254 Updates UI references in styling guides
  packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-themes/index.md
Labels: final review complete

#3259 TBS OKTA-321605 Adds note re SAML 2.0 apps
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Labels: final review complete

#3237 TBS OKTA-456193 Updates redirect auth use cases
  packages/@okta/vuepress-site/.vuepress/public/img/authenticators-email-magic-link-summary-redirect-flow-overview.png
  packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/index.md
Labels: Identity Engine, final review complete

#3288 Rel Notes
  packages/@okta/vuepress-site/docs/release-notes/2022/index.md
Labels: docs release

#3254 Mds/okta 487538 mobile dynamic UI overview
  packages/@okta/vuepress-site/.vuepress/public/img/mobile-sdk/mobile-idx-basic-flow.png
  packages/@okta/vuepress-site/.vuepress/public/img/mobile-sdk/mobile-idx-basic-objects.png
  packages/@okta/vuepress-site/.vuepress/public/img/mobile-sdk/mobile-idx-objects-and-flow.png
  packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/index.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/adddependency.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/dynamicuisample.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/gettingatoken.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/initializingsdksession.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/loadingaconfiguration.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/processresponse.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/redirectquickstart.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/signingout.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/index.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/ios/adddependency.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/ios/dynamicuisample.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/ios/gettingatoken.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/ios/initializingsdksession.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/ios/loadingaconfiguration.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/ios/processresponse.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/ios/redirectquickstart.md
  packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/ios/signingout.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: final review complete
