Repository okta/okta-developer-docs, pull requests merged in 2023-11, with the labels that each got.

#4509 add faq per aaron p
  packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md
Labels: Mark

#4499 okta-506751 Update Self-reg config steps for fed broker mode
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/index.md
Labels: docs update

#4512 OKTA-453644 Add SAML Hook error object content
  packages/@okta/vuepress-site/docs/reference/saml-hook/index.md
Labels: Barbara

#4525 Add WebAuthn Link
  packages/@okta/vuepress-site/docs/reference/api/factors/index.md
Labels: Susan

#4516 OKTA-603844 Updated timeout behaviour in inline hooks concept
  packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
Labels: docs release

#4530 Use alias
  packages/@okta/vuepress-site/docs/reference/api/factors/index.md
Labels: Barbara

#4531 okta-670602 Added webauthn.me link to authenticators-web-authn guide
  packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/index.md
Labels: docs update, Graham

#4532 OKTA-671529 Typo and acrolinx fixes
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-plan-embedded-upgrades/main/index.md
Labels: Graham
