Repository okta/okta-developer-docs, pull requests merged in 2024-02, with the labels that each got.

#4628 Delete $null
  $null
Labels: Barbara

#4629 Added entry to release notes.
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4625 Fix typos in two links
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/go/whatyouneed.md
Labels: Barbara

#4638 lowered score until after release
  .github/acrolinx/global-config.edn
Labels: Graham

#4642 Release Notes entry 2024.02.0
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4635 OKTA-692553 Add ACS URL index restriction for OIN Wizard
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md
Labels: docs release, Barbara

#4634 Guide: Delete all stay signed in sessions
  packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/index.md
  packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Graham

#4633 CAEDD locale updates
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
Labels: docs release, Barbara

#4631 removing DPoP EA flags
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/overview2.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/requestresource.md
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
  packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
Labels: docs release, Barbara

#4636 update dev doc for samlAssertionNotOnOrAfter
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Labels: docs release, Barbara

#4630 Super admin permissions note
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/aotp/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/bmfaotp/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/coobov/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/dmfaoobov/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
Labels: docs release, Barbara

#4645 Minor updates to Password Import and Registration Hook API references
  packages/@okta/vuepress-site/docs/reference/password-hook/index.md
  packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
Labels: Susan

#4609 OKTA-688716 - Revise token hook guide
  packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/nodejs/request.md
Labels: Barbara

#4644 Release 2024.02.0
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/aotp/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/bmfaotp/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/coobov/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/dmfaoobov/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
  packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/index.md
  packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/main/index.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/overview2.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/requestresource.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
  packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release

#4643 Format error fix on CSP pages
  packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
Labels: Barbara

#4637 OKTA-657288 Add appName note in SCIM doc
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md
Labels: Barbara

#4647 OKTA-694229 - Add end user blurb to find your okta domain
  packages/@okta/vuepress-site/docs/guides/find-your-domain/main/index.md
Labels: Barbara

#4657 Remove mentions of session cookies as API auth
  packages/@okta/vuepress-site/docs/guides/enable-cors/main/index.md
  packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
Labels: Graham

#4653 Release 2024.02.1
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4651 OKTA-690935 Fix OIN Wizard doc issues
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-properties.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/test-instance.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/variable-desc.md
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Labels: Graham

#4664 Replace cross-reference in .NET pages
  packages/@okta/vuepress-site/code/dotnet/jwt-validation/index.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/dotnet/accesstoken.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/index.md
Labels: Barbara

#4661 OKTA-696671 Update CLIENT_AS_PRINCIPAL note for org2org and Postman instructions
  packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
  packages/@okta/vuepress-site/docs/reference/rest/index.md
Labels: Barbara

#4667 Product Name Corrections
  packages/@okta/vuepress-site/docs/concepts/iam-overview-authentication-factors/index.md
  packages/@okta/vuepress-site/docs/concepts/interaction-code/index.md
  packages/@okta/vuepress-site/docs/concepts/saml/index.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/interactioncode/configuration.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/interactioncode/flow-diagram.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/android/signout.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/springboot/createproject.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/springboot/independ.md
  packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/ios/simpleenrollauth.md
  packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/ios/toolnote.md
  packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/ios/tryenrollin.md
  packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/reactnativeios/simpleenrollauth.md
  packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/reactnativeios/toolnote.md
  packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/reactnativeios/tryenrollin.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
Labels: Graham

#4670 OKTA-697917 -Weekly release notes entry
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#4673 OKTA-700333 - Add redirect
  packages/@okta/vuepress-site/conductor.yml
Labels: Barbara

#4674 OKTA-695739 Add Postman instruction link to API principles page
  packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
Labels: Graham

#4675 OKTA-700802 Update login.gov links
  packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md
Labels: Graham

#4679 Removed Early Access flag. OKTA-702016.
  packages/@okta/vuepress-site/docs/reference/api/users/index.md
Labels: Susan
