Repository okta/okta-developer-docs, pull requests merged in 2024-06, with the labels that each got.

#4857 Custom email guide: add table of supported languages
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
Labels: Barbara

#4860 baseline push
  .github/acrolinx/repositories.edn
Labels: Barbara

#4841 OKTA-731717 - Update number of inline hooks
  packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
  packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
Labels: docs release, Susan

#4858 Custom email guide: edit to language for extra locales
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
Labels: Graham

#4855 OKTA-725768 Update name description for OIN and custom apps API
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Labels: Barbara

#4817 OKTA-727230 Add new event type
  packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
Labels: docs release, Barbara

#4862 Release 2024.06.0
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
  packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
  packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
  packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4869 Brands API: Fixes broken links pointing from DOC to Redocly
  packages/@okta/vuepress-site/docs/concepts/brands/index.md
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/brands/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#4870 Brands API: Deprecate page from VuePress
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-manage-end-user-experience/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/brands/index.md
  packages/@okta/vuepress-site/docs/reference/api/org/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#4872 lowering score for fixitdays
  .github/acrolinx/global-config.edn
Labels: Graham

#4874 FIXIT DAY [OKTA-729831] - placeholder update
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/basic-sign-in.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/download-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/basic-sign-in.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/download-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/sign-in-form.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/download-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/load-app.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/run-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/load-app.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/run-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/useaccesstoken.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/configmid.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/configmid.md
  packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/go/configmid.md
Labels: Susan

#4875 Placeholder updates part 2
  packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md
  packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/configlocations.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/configlocations.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/configlocations.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/softwarerequirements.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/configlocations.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/react/configlocations.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/java/runsdkapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/java/runwidgetapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/emailtemplate.md
  packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/node-express/configmid.md
  packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/spring-boot/configmid.md
Labels: Susan

#4878 Placeholders pt 4
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/afterappidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-access-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/main/index.md
  packages/@okta/vuepress-site/docs/guides/email-magic-links-overview/main/index.md
  packages/@okta/vuepress-site/docs/guides/enable-cors/main/index.md
  packages/@okta/vuepress-site/docs/guides/find-your-app-credentials/main/index.md
  packages/@okta/vuepress-site/docs/guides/find-your-domain/main/index.md
  packages/@okta/vuepress-site/docs/guides/policy-simulation/main/index.md
  packages/@okta/vuepress-site/docs/guides/single-logout/main/index.md
  packages/@okta/vuepress-site/docs/guides/single-logout/main/openidconnect/getrequest.md
  packages/@okta/vuepress-site/docs/guides/single-logout/main/saml2/getrequest.md
  packages/@okta/vuepress-site/docs/guides/single-logout/main/saml2/putrequest.md
  packages/@okta/vuepress-site/docs/guides/single-logout/main/saml2/response.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
Labels: Susan

#4877 [OKTA-729831] placeholders pt 3
  packages/@okta/vuepress-site/docs/guides/device-context/main/aspnet/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/device-context/main/nodeexpress/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/sdk.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/siw.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/java/emailtemplate.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/java/sdk.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/java/siw.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/emailtemplate.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/sdk.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/siw.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-new-user-activation/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-new-user-activation/main/nodeexpress/proxymodelsampleappactivationtokenlink.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-soc-idp/main/aspnet/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/aspnet/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/go/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/java/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/nodejs/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/go/integrationsteps.md
Labels: Susan

#4871 OKTA-736503 - Minor updates to vanilla spa app
  packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
Labels: Barbara

#4879 clarity update for oauth oidc concept
  packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md
Labels: Graham

#4880 Fix-It Days: Placeholders 1 (Brent)
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-sms-messaging/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
Labels: Barbara

#4882 Fix-It Days: Placeholder revert on Velocity Templating Language
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
Labels: Barbara

#4881 placeholder removal for auth servers
  packages/@okta/vuepress-site/docs/concepts/auth-servers/index.md
Labels: Barbara

#4883 Fix-It Days: Placeholders 2 (Brent)
  packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
Labels: Graham

#4884 Placeholders in Classic
  packages/@okta/vuepress-site/docs/guides/archive-auth-js/main/index.md
  packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/angular/guide.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/react/guide.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/vue/guide.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/angular/guide.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/react/guide.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/vue/guide.md
  packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/android/primaryauth.md
  packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/ios/primaryauth.md
  packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/react-native/installoktaauthsdk.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/ga/activatefactor.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/ga/enrollfactor.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/ga/verifyfactor.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/sms/activatefactor.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/sms/verifyfactor.md
  packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/main/android/configfile.md
  packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/main/ios/enablesso.md
  packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/main/index.md
  packages/@okta/vuepress-site/docs/guides/updating-saml-cert/main/index.md
Labels: Barbara

#4887 clarity and $ removal for refresh tokens
  packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
Labels: Barbara

#4888 More placeholder changes for oie-upgrade-* files
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/android/addsdk.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/java/addsdk.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/android/auth-vs-oie.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/java/auth-vs-oie.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-mfa-enroll-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sessions-api/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-deprecated-methods/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
Labels: Barbara

#4885 Fix-it-day placeholders for OIN section (Van)
  packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md
  packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/scim/submit.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/variable-desc.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/variable-desc.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/openidconnect/submit.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/saml2/submit.md
Labels: Barbara

#4890 Fit-it-day placeholder updates API Security > protect-your-api (Van)
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/aspnetcore3/configureapi.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/go/configureapi.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/nodeexpress/configureapi.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/python/configureapi.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/springboot/configureapi.md
Labels: Graham

#4894 Aj okta729831 placeholder 8
  packages/@okta/vuepress-site/docs/concepts/scim/faqs/index.md
  packages/@okta/vuepress-site/docs/concepts/scim/index.md
Labels: Susan

#4896 Fix-It Days: Placeholders 3 (Brent)
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
Labels: Graham

#4893 Fix-it-day placeholder updates hook concepts
  packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
  packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
  packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
Labels: Susan

#4897 aj-okta729831-placeholder-10
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#4895 Fit-it-day placeholder update for Deploy to Production (Van)
  packages/@okta/vuepress-site/docs/guides/deploy-your-app/main/java/deployment.md
  packages/@okta/vuepress-site/docs/guides/deploy-your-app/main/javascript/deployment.md
  packages/@okta/vuepress-site/docs/guides/deploy-your-app/main/reactnative/deployment.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-bulk/main/index.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-password-hooks/main/index.md
Labels: Graham

#4898 Fit-it-day placeholder updates for test with Postman (Van)
  packages/@okta/vuepress-site/docs/reference/rest/index.md
Labels: Graham

#4899 doc action removal
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4889 Fit-it-day Placeholders for API Security (Van )
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/claims.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/initialrequest.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/payload.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/payload2.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/refresh.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/claims.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/diagram.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/initialrequest.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/payload.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/payload2.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/refresh.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/requestresource.md
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
  packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
  packages/@okta/vuepress-site/docs/guides/step-up-authentication/main/index.md
  packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/main/index.md
Labels: Susan

#4901 Placeholders
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Labels: Graham

#4904 Hooks guides placeholder updates
  packages/@okta/vuepress-site/docs/guides/event-hook-filtering/main/index.md
  packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
  packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/main/nodejs/password-import-api.md
  packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
Labels: Susan

#4905 Fix-It Days: Placeholders 4 (Brent)
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/aotp/use-flow.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/bmfaotp/use-flow.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/coobov/use-flow.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/dmfaoobov/use-flow.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/use-flow.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/use-flow.md
  packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/use-flow.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/use-flow.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/use-flow.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/use-flow.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/use-flow.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/configuration.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/use-flow.md
Labels: Graham

#4902 Clarity and $ updates
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/dotnet/accesstoken.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/dotnet/retrievekeys.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/go/accesstoken.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/go/retrievekeys.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/index.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/java/accesstoken.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/java/retrievekeys.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/nodejs/accesstoken.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/nodejs/retrievekeys.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/python/accesstoken.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/python/retrievekeys.md
Labels: Barbara

#4906 Fix-It Days: Placeholders 5 (Brent)
  packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md
  packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/java/createclientsecretjwt.md
  packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/java/createprivatekeyjwt.md
  packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/js/createclientsecretjwt.md
  packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/js/createprivatekeyjwt.md
  packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
  packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
  packages/@okta/vuepress-site/docs/guides/set-up-token-exchange/main/index.md
Labels: Barbara

#4907 Fix-It Days: Placeholders 6 (Brent)
  packages/@okta/vuepress-site/docs/guides/revoke-tokens/main/index.md
  packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/dotnet/accesstoken.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/go/accesstoken.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/java/accesstoken.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/nodejs/accesstoken.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/python/accesstoken.md
Labels: Graham

#4909 OAuth for Okta Service App FixtIt Day Clarity Update
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
Labels: Graham

#4910 Auth Code with PKCE updates
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/examples.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/flow-diagram.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/install-sdk.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/overview.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/setup-app.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/use-flow.md
Labels: Barbara

#4911 client cred update
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/flow-diagram.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/install-sdk.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/overview.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/use-flow.md
Labels: Barbara

#4868 OKTA-736868 - Rate Limits - Update DynamicScale endpoints
  packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
  packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
Labels: Susan

#4840 OKTA-731799 Update Entity Risk Policy detected risk event enums
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
Labels: docs release, Susan

#4914 OKTA-734468 Add 2024.06.1 RN entries
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#4915 OKTA-734468 Release Notes 2024.06.1
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: docs release, Barbara

#4918 Push Providers API: deprecate VuePress page, etc.
  packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/notifserviceadminconsole.md
  packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/notifserviceadminconsole.md
  packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
  packages/@okta/vuepress-site/docs/reference/api/push-providers/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#4919 OKTA-740742 Update Role description and link
  packages/@okta/vuepress-site/docs/concepts/iam-overview-iam-terminology/index.md
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
Labels: Barbara

#4925 Update false positives list
  falsepos.txt
Labels: Barbara

#4913 OKTA-735460 - Update CAE content in Policies Concept
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
Labels: Susan

#4928 deprecating templates API
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/custom-sms-messaging/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/factors/index.md
  packages/@okta/vuepress-site/docs/reference/api/templates/index.md
  packages/@okta/vuepress-site/docs/release-notes/2016/index.md
  packages/@okta/vuepress-site/docs/release-notes/2020/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#4927 OKTA-729928 Add considerations for editing AIP variables in migrated OIN apps
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: Susan
