Repository okta/okta-developer-docs, pull requests merged in 2024-10, with the labels that each got.

#5108 [OKTA-798712] TOC and links changes
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
  packages/@okta/vuepress-site/docs/concepts/iam-overview-architectural-factors/index.md
  packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
  packages/@okta/vuepress-site/docs/concepts/monitor/index.md
  packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
  packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md
  packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
  packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/index.md
  packages/@okta/vuepress-site/docs/guides/oin-api-service-overview/index.md
  packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/archive-myaccount/index.md
  packages/@okta/vuepress-site/docs/reference/api/authn/index.md
  packages/@okta/vuepress-site/docs/reference/api/event-types/index.md
  packages/@okta/vuepress-site/docs/reference/api/factors/index.md
  packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
  packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md
  packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
  packages/@okta/vuepress-site/docs/reference/user-query/index.md
  packages/@okta/vuepress-site/docs/release-notes/2017/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
  packages/@okta/vuepress-theme-prose/global-components/ApiAuthMethodWarning.vue
Labels: Susan

#5113 Broken link
  packages/@okta/vuepress-site/docs/reference/index.md
Labels: Susan

#5114 Removed banner from Reference overview page.
  packages/@okta/vuepress-site/docs/reference/index.md
Labels: Barbara

#5118 Add IdP and OIDC acronyms where appropriate
  packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/main/index.md
  packages/@okta/vuepress-site/docs/guides/step-up-authentication/main/index.md
Labels: Barbara

#5121 OKTA-814729 Update OIN catalog use case categories
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
Labels: Barbara

#5123 [OKTA-807736] Limitations in XaaS
  packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
Labels: Barbara

#5126 OKTA-815376 Remove EA for access cert and request roles
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
Labels: Barbara

#5119 OKTA-807237 - Add note regarding dynamic scale to rl pages
  packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
  packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
  packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
  packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
  packages/@okta/vuepress-site/docs/reference/rl-global-mgmt/index.md
Labels: Barbara

#5132 Another link
  packages/@okta/vuepress-site/docs/reference/api/users/index.md
Labels: Graham

#5134 OKTA-506229 Updated version numbers for Angular SIW sample
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/download-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/intro.md
Labels: docs update, Barbara

#5107 Updates for strict account linking
  packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/accountlink.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/accountlinking2.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/createidpnote.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/accountlink.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/accountlinking2.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/createidpnote.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/accountlink.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/accountlinking2.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/createidpnote.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/accountlink.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/accountlinking2.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/createidpnote.md
  packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
Labels: Barbara

#5136 [OKTA-812814] ID tokens
  packages/@okta/vuepress-site/docs/guides/validate-id-tokens/main/index.md
Labels: Susan

#5133 [OKTA 806255/805433] Expression language fixes
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Labels: Barbara

#5138 Release 2024.10.0
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/.vuepress/public/img/homepage/SDKs-menu.png
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
  packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/oin-lifecycle-mgmt-overview/index.md
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/index.md
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-overview/main/index.md
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/index.md
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-test/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-properties.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-test-flow.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/test-instance.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-test-flow.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/test-instance.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/backward-compatible-eg.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/protocol-fullname.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/protocol-name.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/protocol-properties.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/protocol-test-flow.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/see-also.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/test-instance.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/variable-desc.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#5141 OKTA-818938 - Rate Limits overview minor update
  packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
Labels: Barbara

#5142 Very minor updates to Test APIs with Postman
  packages/@okta/vuepress-site/docs/reference/rest/index.md
Labels: Susan

#5143 DPoP updates
  packages/@okta/vuepress-site/docs/guides/dpop/main/index.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/claims.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/diagram.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/glitch.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/iat.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/payload.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/requestresource.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/whatyouneed.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/claims.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/diagram.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/iat.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/payload.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/requestresource.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/whatyouneed.md
Labels: Graham

#5146 Re-add link to blurb in 2024.10.0 release notes
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
Labels: Barbara

#5129 OKTA-800843 - Updated embedded auth SPA guides
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/download-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/basic-sign-in.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/sign-in-form.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/sign-in-form.md
Labels: Barbara

#5135 add OIDC to group sync support
  packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md
Labels: docs release

#5152 clarity updates
  packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md
Labels: Barbara

#5156 clarity work
  packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
Labels: Barbara

#5161 OKTA-405221 Fixed incorrect parameter in response sample
  packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
Labels: Barbara

#5163 Align scopes with samples for React and Angular
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/configmid.md
Labels: Barbara
