Repository okta/okta-developer-docs, pull requests merged in 2024-05, with the labels that each got.

#4784 SIW Gen3 - Document afterRender revert
  packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
Labels: Barbara

#4796 Update DNSSEC note
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
Labels: Barbara

#4799 SIW (Gen3) - fix broken link
  packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
Labels: Susan

#4788 OKTA-716079 - Add new target property to System Log API
  packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
Labels: docs release, Susan

#4809 Add post-release fix
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4810 Release 2024.05.0 - SSF Transmitter API doc link
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
Labels: Graham

#4820 Release notes entries for 2024.05.1 release
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4822 [OKTA-726563] 2024.05.1 release
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4823 [OKTA-408401] OEL update
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Labels: Susan

#4827 updates to device auth
  packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
Labels: Graham

#4832 dpop link
  packages/@okta/vuepress-site/conductor.yml
Labels: Graham

#4829 OKTA-728721 Update SCIM 2.0 test plan with error and response handling
  packages/@okta/vuepress-site/.vuepress/public/standards/SCIM/SCIMFiles/Okta-SCIM-20-SPEC-Test.json
Labels: Susan

#4605 OKTA-520454 Add group exists operation to SCIM protocol
  packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
  packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
Labels: Susan

#4838 OKTA-731746 - RL overview clarification
  packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
Labels: Graham

#4839 SIW3 - Add description of palette generation and accessibility
  packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4844 Fix Parmonic broken link
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
Labels: Graham

#4845 OKTA-728721 Update SCIM 2 test file
  packages/@okta/vuepress-site/.vuepress/public/standards/SCIM/SCIMFiles/Okta-SCIM-20-SPEC-Test.json
Labels: Barbara

#4849 [OKTA-730760] Content issues in guide
  packages/@okta/vuepress-site/docs/guides/scim-with-entitlements/main/index.md
Labels: Susan

#4847 Update Parmonic doc link
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
Labels: Barbara

#4851 OKTA-730160 - AIP variable name format
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: Graham

#4850 OKTA-731746 - Minor update to RL overview
  packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
Labels: Susan

#4854 OKTA-520454 SCIM reference update for the GET /Groups with filtering request
  packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
  packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
Labels: Barbara

#4856 [OKTA-734890] Remove item in Release Notes
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara
