Repository okta/okta-developer-docs, pull requests merged in 2024-04, with the labels that each got.

#4742 note about client credentials and org/custom auth servers
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/overview.md
Labels: Barbara

#4747 Okta Aerial: small fix
  packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md
Labels: Susan

#4746 OKTA-707879 Post 2024.03.2 prod deploy RN
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#4748 RN entries for 2024.04.0
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#4621 OKTA-673872 - Identity Threat Protection - Policy API and Policies Concept Updates
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: docs release, Barbara, Graham

#4705 OKTA-703920 - ITP event documentation
  packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
  packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
Labels: docs release, Barbara

#4737 OKTA-705616 Provisioning connection guide updates with OAuth2 API access
  packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md
Labels: docs release, Susan

#4722 Added agents permissions for OKTA-702597.
  packages/@okta/vuepress-site/docs/reference/api/roles/index.md
Labels: docs release, Susan

#4750 Specify that multiple scopes must be separated by spaces.
  packages/@okta/vuepress-site/docs/reference/rest/index.md
Labels: Barbara

#4749 2024.04.0 - Release branch
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/reference/api/roles/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
  packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
  scripts/update-error-codes.sh
  scripts/update-event-types.sh
  scripts/update-oauth2-error-codes.sh
Labels: Barbara

#4751 Fix broken link
  packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
Labels: Barbara

#4752 Moved to proper section.
  packages/@okta/vuepress-site/docs/reference/rest/index.md
Labels: Barbara

#4753 Updated link to developer topic.
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara, Graham

#4754 Updated formatting for consistency.
  packages/@okta/vuepress-site/docs/reference/api/roles/index.md
Labels: Graham

#4755 Fix two local URLs
  packages/@okta/vuepress-site/archive/php/protect-your-api/index.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md
Labels: Barbara

#4757 Add ITP SSF API links to 2024.04.0 release notes
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
Labels: Graham

#4759 Add two redirects to conductor.yaml file
  packages/@okta/vuepress-site/conductor.yml
Labels: Graham

#4756 Custom domains: add network zones note
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
Labels: Graham

#4758 Policy API: Adds multiple IDs
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
Labels: docs release, Graham

#4760 Multiple IDs - main
  packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/index.md
Labels: Barbara

#4763 Weekly Release Notes PR - 2024.04.1
  packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
Labels: Graham

#4761 first set of updates for nut facts and acrolinx scores
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
  packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
  packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md
  packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-email/main/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/index.md
  packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/index.md
  packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md
  packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-access-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/aotp/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/bmfaotp/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/coobov/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/dmfaoobov/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/nutrition.md
  packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-user-scoped-account-management/main/index.md
  packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-sms-messaging/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
Labels: Graham

#4764 pointing to hoc for create an API token content
  packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
Labels: Barbara

#4765 org2org and amr claims mapping update
  packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
Labels: Graham

#4767 Second set of nut fact and acrolinx updates
  packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
  packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/main/index.md
  packages/@okta/vuepress-site/docs/guides/deploy-your-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
  packages/@okta/vuepress-site/docs/guides/device-context/main/index.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/index.md
  packages/@okta/vuepress-site/docs/guides/email-magic-links-overview/main/index.md
  packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md
  packages/@okta/vuepress-site/docs/guides/enable-cors/main/index.md
  packages/@okta/vuepress-site/docs/guides/event-hook-filtering/main/index.md
  packages/@okta/vuepress-site/docs/guides/event-hook-hookdeck/main/index.md
  packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
  packages/@okta/vuepress-site/docs/guides/event-hook-ngrok/main/index.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/nutrition.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/nutrition.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/nutrition.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/interactioncode/nutrition.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/nutrition.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/nutrition.md
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
  packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/index.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-bulk/main/index.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-password-hooks/main/index.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-prerequisites/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/index.md
Labels: Barbara

#4769 Policies Concept - Update to number of rules
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
Labels: Graham

#4766 OKTA-718253 - Fixes to ERP and CAE Policy Types in Policy API
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
Labels: Graham

#4773 Nut Facts and Acrolinx - round 4
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-overview/main/index.md
  packages/@okta/vuepress-site/docs/guides/scim-with-entitlements/main/index.md
  packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
  packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
  packages/@okta/vuepress-site/docs/guides/set-up-token-exchange/main/index.md
  packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/main/index.md
  packages/@okta/vuepress-site/docs/guides/sharing-cert/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-users-out/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/main/index.md
  packages/@okta/vuepress-site/docs/guides/single-logout/main/index.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
  packages/@okta/vuepress-site/docs/guides/step-up-authentication/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-design-rate-limits/main/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-manage-end-user-experience/main/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-manage-external-authenticators/main/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-manage-groups/main/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-manage-user-access/main/index.md
  packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/main/index.md
  packages/@okta/vuepress-site/docs/guides/updating-saml-cert/main/index.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/index.md
  packages/@okta/vuepress-site/docs/guides/validate-id-tokens/main/index.md
Labels: Barbara, Graham

#4774 OKTA-689678 - Hook doc set updates
  packages/@okta/vuepress-site/docs/guides/event-hook-filtering/main/index.md
  packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
  packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
  packages/@okta/vuepress-theme-prose/global-components/HookBasicAuthValuesNote.vue
  packages/@okta/vuepress-theme-prose/global-components/HookCommonSetupNote.vue
Labels: Susan

#4663 OKTA-696571 Update client as principal in service app guide
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
Labels: Barbara

#4538 Release note project: updates for SEO
  packages/@okta/vuepress-site/.vuepress/config.js
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-site/docs/release-notes/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Graham

#4782 OKTA-721763 Add no SPA app support in OIN Wizard
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: Susan

#4785 SSR guide (archived) - Small updates
  packages/@okta/vuepress-site/docs/guides/archive-set-up-self-service-registration/main/index.md
Labels: Barbara

#4780 Update to OIE overview page for PATEAM
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
Labels: Graham
