Repository okta/okta-developer-docs, pull requests merged in 2024-12, with the labels that each got.

#5228 adding microsoft note
  packages/@okta/vuepress-site/docs/guides/social-login/main/amazon/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/apple/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/discord/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/facebook/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/github/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/gitlab/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/google/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/linkedin/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/microsoft/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/paypal/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/salesforce/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/spotify/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/xero/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/yahoo/micronote.md
  packages/@okta/vuepress-site/docs/guides/social-login/main/yahoojp/micronote.md
Labels: Graham

#5227 OKTA-837437 Fix formatting issue with notes
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/getuserprofile.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/pwdoptionalusecase.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/go/getuserprofile.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/ios/getuserprofile.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/ios/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/getuserprofile.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/pwdoptionalusecase.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/getuserprofile.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/pwdoptionalusecase.md
Labels: Barbara

#5229 OKTA-838336 Update OIN SAML limitations
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/protocol-properties.md
Labels: Barbara

#5231 Release 2024.11.2
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Susan

#5185 OAMP GA
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/main/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
Labels: docs release, Barbara

#5166 OKTA-822501 - Add account linking condition features
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/afterappidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/afterappidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/afterappidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
Labels: docs release, Susan

#5122 OKTA-795656 OIN Wizard: new Use Cases field and automatic use case assignment
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: docs release, Susan

#5233 OKTA-840636 Add SCIM server test credentials in Testing Instructions field
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: Barbara

#5215 OKTA-809675 Remove SCIM from OIN Manager
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/scim/protocol-name.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/scim/see-also.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/scim/submit.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/wfconnector/protocol-name.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Graham

#5241 Release 2024.12.0
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
Labels: Susan

#5260 [OKTA-847065] Note to Postman Collections page
  packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
  packages/@okta/vuepress-site/docs/reference/rest/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara
