Repository okta/okta-developer-docs, pull requests merged in 2024-08, with the labels that each got.

#4987 Release Branch - 2024.07.2
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/index.md
  packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#4921 OKTA-736640 - Add new event type
  packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
  packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
Labels: docs release, Brent

#4981 Custom domains: update TLS cert and key info
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
Labels: docs release, Graham

#4983 OKTA-753712 - Update CAE references
  packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
Labels: docs release, Barbara

#4982 OKTA-742877 - Update ITP event type names
  packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
  packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
Labels: docs release, Graham

#5001 Release 2024.08.0
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
Labels: Barbara

#5002 OKTA-790486 - Temp updates to Event Types json
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/data/event-types.json
Labels: Susan

#5006 Added note to emphasise using redirect authentication.
  packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md
Labels: Barbara

#5007 OKTA-753712 - Address a few overwritten terminology updates
  packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
Labels: Susan

#5009 Minor format updates to refresh token guide
  packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
Labels: Barbara

#5003 OKTA-756629 - Update CAE policies vuepress
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
Labels: Barbara

#5012 OKTA-744012 RN entries for 2024.08.1
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: docs release

#5013 OKTA-744012 Release Notes for 2024.08.1
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: docs release, Barbara

#5014 OKTA-754148 - Updating scripts to include changeDetails info
  packages/@okta/vuepress-site/docs/reference/api/event-types/index.md
  packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
  scripts/event-types-to-csv.sh
Labels: Barbara

#5017 Groups Vuepress page deprecation
  packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/groups.json
  packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
  packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md
  packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-bulk/main/index.md
  packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/policy-simulation/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
  packages/@okta/vuepress-site/docs/reference/api/groups/index.md
  packages/@okta/vuepress-site/docs/reference/api/roles/index.md
  packages/@okta/vuepress-site/docs/reference/api/users/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
Labels: Barbara

#5018 OKTA 694578 Delete archived topic
  packages/@okta/vuepress-site/archive/index.md
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/archive-overview/main/index.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/index.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/angular/guide.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/react/guide.md
  packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/vue/guide.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/nutrition.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#5019 deprecation of Dynamic Client Registration
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/setup-app.md
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
  packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
  packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md
  packages/@okta/vuepress-site/docs/release-notes/2017/index.md
  packages/@okta/vuepress-site/docs/release-notes/2018/index.md
  packages/@okta/vuepress-site/docs/release-notes/2020/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Graham

#5020 Authorization Server deprecation
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md
  packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
  packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
  packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
  packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
  packages/@okta/vuepress-site/docs/guides/revoke-tokens/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md
  packages/@okta/vuepress-site/docs/release-notes/2017/index.md
  packages/@okta/vuepress-site/docs/release-notes/2018/index.md
  packages/@okta/vuepress-site/docs/release-notes/2019/index.md
  packages/@okta/vuepress-site/docs/release-notes/2020/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5005 Updates and acrolinx
  packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
Labels: Barbara

#5000 Update index.md
  packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
Labels: Susan

#5022 Removing AMR blurb
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
Labels: Graham

#5021 OKTA-794463 - OIN landing page update
  packages/@okta/vuepress-theme-prose/custom-landings/OktaIntegrationNetwork/components/Explore.vue
  packages/@okta/vuepress-theme-prose/custom-landings/OktaIntegrationNetwork/components/Features.vue
Labels: Barbara

#5004 OKTA-520613 Updates to global session policy page
  packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
Labels: Graham

#5027 factors deprecation
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
  packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/index.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/nodejs/auth-vs-oie.md
  packages/@okta/vuepress-site/docs/reference/api/factors/index.md
  packages/@okta/vuepress-site/docs/release-notes/2016/index.md
  packages/@okta/vuepress-site/docs/release-notes/2017/index.md
  packages/@okta/vuepress-site/docs/release-notes/2018/index.md
  packages/@okta/vuepress-site/docs/release-notes/2019/index.md
  packages/@okta/vuepress-site/docs/release-notes/2020/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
  tests/cypress/integration/page_content_spec.js
Labels: Graham

#5029 Tiny changes
  packages/@okta/vuepress-site/docs/guides/saml-tracer/main/index.md
Labels: Susan

#5024 OKTA-744014-Weekly release notes
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#5031 Minor update to code snippet
  packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
Labels: Barbara

#5032 Update outdated links
  packages/@okta/vuepress-site/conductor.yml
Labels: Graham

#5008 OKTA-745365 - Added scopes for refresh token use to SPA guides
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/configmid.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/configmid.md
Labels: Barbara

#5028 OKTA-793295 - Add note to create a child org section of Aerial guide
  packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md
Labels: Susan, Graham

#5042 Recreated PR 5034
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-deprecated-methods/main/index.md
Labels: Graham

#5039 Release 2024.08.3
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Susan

#5044 OKTA-794269 Acrolinx improvement edits
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
Labels: Graham

#5041 [OKTA-740614] Linked Objects deprecation
  packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md
Labels: Barbara
