Repository okta/okta-developer-docs, pull requests merged in 2024-07, with the labels that each got.

#4934 updated diagram for AMR claims mapping
  packages/@okta/vuepress-site/.vuepress/public/img/auth/amr-claims-mapping-oidc.png
  packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
Labels: Barbara

#4937 [OKTA-543635] Reserved attributes in SCIM
  packages/@okta/vuepress-site/docs/concepts/scim/faqs/index.md
Labels: Susan

#4936 removing self-service EA bullet
  packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md
Labels: Graham

#4924 Authenticators API: Deprecate docs from VuePress
  packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/customauthenticatoradminconsole.md
  packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/customauthenticatoradminconsole.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-mfa-enroll-policy/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Graham

#4944 Edits on the Enable CORS topic with GPG
  packages/@okta/vuepress-site/docs/guides/enable-cors/main/index.md
Labels: Barbara

#4940 OKTA-738761 Add OEL guidance for dynamic OIN OIDC and SAML properties
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-properties.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/variable-desc.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/variable-desc.md
Labels: Barbara

#4945 OIE Expression Language: New expressions for account mgmt policy
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
Labels: DO NOT MERGE, Barbara

#4938 OKTA-745788 - Event Hook org limit update
  packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
  packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
Labels: docs release, Barbara

#4935 hide files
  packages/@okta/vuepress-site/.vuepress/config.js
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Graham

#4948 OKTA-742371 Doc gap: add API token permissions
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
  packages/@okta/vuepress-site/docs/reference/api/roles/index.md
Labels: Susan

#4943 OKTA-746030 - Update Aerial dev guide
  packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md
Labels: Barbara

#4950 Edits on the IAM overview topic
  packages/@okta/vuepress-site/docs/concepts/iam-overview/index.md
Labels: Susan

#4949 Release 2024.07.0 - Release Notes and doc updates
  packages/@okta/vuepress-site/.vuepress/config.js
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
  packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
  packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#4953 OKTA-747879 - Remove ITP EA banners
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
Labels: Susan

#4954 OKTA-747426 - Update to 2024.06.2 RN
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4957 [OKTA 748328] Nav bar fix for Group Owners API
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Graham

#4947 [OKTA-725988] Schemas API Vuepress page deprecation
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md
  packages/@okta/vuepress-site/docs/reference/api/archive-myaccount/index.md
  packages/@okta/vuepress-site/docs/reference/api/groups/index.md
  packages/@okta/vuepress-site/docs/reference/api/log-streaming/index.md
  packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
  packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
  packages/@okta/vuepress-site/docs/reference/api/user-types/index.md
  packages/@okta/vuepress-site/docs/reference/api/users/index.md
  packages/@okta/vuepress-site/docs/release-notes/2016/index.md
  packages/@okta/vuepress-site/docs/release-notes/2017/index.md
  packages/@okta/vuepress-site/docs/release-notes/2018/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#4926 OKTA-743092 Add notes regarding OIN SSO migration
  packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md
Labels: Barbara

#4960 SCIM clarity fix
  packages/@okta/vuepress-site/docs/concepts/scim/index.md
Labels: Barbara

#4965 SIW Gen 3 guide: remove extra OIE tag
  packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
Labels: Susan

#4964 OKTA-749502 - Update ITP event types doc
  packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
Labels: Graham

#4967 Weekly Release 2024.07.1
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Susan

#4968 Event Types - set workflow events to publish
  packages/@okta/vuepress-site/data/event-types.json
Labels: Graham

#4966 Adding note to Embedded SIW guide
  packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md
Labels: Barbara

#4980 Custom email notification guide: remove JavaScript mentions
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
Labels: Graham

#4978 Edits to improve acro score
  packages/@okta/vuepress-site/docs/guides/find-your-domain/main/index.md
Labels: Graham

#4977 Edit Create and API token page to improve Acro score
  packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
Labels: Graham

#4959 Okta account management policy - main
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/index.md
  packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Graham

#4988 remove sigining in with email
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
Labels: Barbara

#4956 Failover content for Telephony Inline Hook
  packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
Labels: Barbara
