Repository okta/okta-developer-docs, pull requests merged in 2024-01, with the labels that each got.

#4565 Update index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
Labels: Mark

#4566 OKTA-678524 - OIE Expression Language guide updates
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
Labels: docs release

#4560 pkce parameter
  packages/@okta/vuepress-site/docs/reference/api/idps/index.md
Labels: Graham

#4570 Release 2023.12.2
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
Labels: Graham

#4567 Add section on securing service app with an admin role
  packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md
Labels: final edit ready, Mark

#4573 refresh token lifetime clarifications
  packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md
Labels: Graham

#4572 Post-release bug 2023.12.2
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
Labels: Mark

#4577 Add alias reference to product docs
  packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md
Labels: Susan

#4415 OKTA-631100 New ISV submission experience with OIN Wizard
  packages/@okta/vuepress-site/.vuepress/public/img/oin/OIN_Wizard_submission_flow_SSO.png
  packages/@okta/vuepress-site/.vuepress/public/img/oin/isv-portal_submission_flow.png
  packages/@okta/vuepress-site/.vuepress/public/img/oin/isv_portal_submission_flow_LCM.png
  packages/@okta/vuepress-site/.vuepress/public/img/oin/publicOrPrivateIntegration.png
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/add-private-app/index.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/create.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/see-also.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/settings.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/test.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/saml2/create.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/saml2/see-also.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/saml2/settings.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/saml2/test.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/see-also.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/settings.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/saml2/see-also.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/saml2/settings.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/oin-sso-overview/index.md
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-test/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/backward-compatible-eg.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-fullname.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-name.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-properties.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-test-flow.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/see-also.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/test-instance.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/variable-desc.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/backward-compatible-eg.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-fullname.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-name.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-test-flow.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/see-also.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/test-instance.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/variable-desc.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, final review complete, Susan

#4578 OKTA-681413 Release note entries for 2024.01.0
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#4579 OKTA-681413 Release notes for 2024.01.0
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/.vuepress/public/img/oin/OIN_Wizard_submission_flow_SSO.png
  packages/@okta/vuepress-site/.vuepress/public/img/oin/isv-portal_submission_flow.png
  packages/@okta/vuepress-site/.vuepress/public/img/oin/isv_portal_submission_flow_LCM.png
  packages/@okta/vuepress-site/.vuepress/public/img/oin/publicOrPrivateIntegration.png
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
  packages/@okta/vuepress-site/docs/guides/add-private-app/index.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/create.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/see-also.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/settings.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/test.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/saml2/create.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/saml2/see-also.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/saml2/settings.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/saml2/test.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/see-also.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/settings.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/saml2/see-also.md
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/saml2/settings.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/oin-sso-overview/index.md
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-test/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/backward-compatible-eg.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-fullname.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-name.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-properties.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-test-flow.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/see-also.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/test-instance.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/variable-desc.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/backward-compatible-eg.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-fullname.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-name.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-test-flow.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/see-also.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/test-instance.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/variable-desc.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#4583 Update copyright year
  packages/@okta/vuepress-site/copyright/index.md
Labels: Susan

#4587 IAM_READ_RESOURCES - Update permission types and resource objects
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
  packages/@okta/vuepress-site/docs/reference/api/roles/index.md
Labels: Barbara

#4586 remove limitations bullet
  packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
Labels: Graham

#4598 Remove old email alias
  packages/@okta/vuepress-site/docs/reference/api/captchas/index.md
  packages/@okta/vuepress-site/docs/reference/api/devices/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/pricing/index.md
Labels: Susan

#4597 Release 2024.01.1
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
Labels: Barbara

#4600 OKTA-620023 Update basic sdk sign in guide
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-android-sign-in-pwd-only-flow-diagram.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-dotnet-sign-in-pwd-only-flow-diagram.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-go-sign-in-pwd-only-flow-diagram.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-java-sign-in-pwd-only-flow-diagram.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-nodejs-sign-in-pwd-only-flow-diagram.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-go-use-case-basic-sign-on.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-use-case-simple-sign-on-seq-java.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-use-case-simple-sign-on-seq-nodejs.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-use-case-simple-sign-on-seq.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-use-case-swift-basic-sign-in-pwd.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-swift-sign-in-pwd-only-flow-diagram.png
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/android/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/android/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/android/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/android/whatyouneed.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/getuserprofile.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/pwdoptionalusecase.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/samplecode.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/whatyouneed.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/go/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/go/getuserprofile.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/go/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/go/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/go/whatyouneed.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/ios/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/ios/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/ios/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/ios/whatyouneed.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/getuserprofile.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/samplecode.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/whatyouneed.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/getuserprofile.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/whatyouneed.md
Labels: docs update

#4602 Update hasDirectoryUser() description
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Labels: Graham

#4604 Minor update to release note titles
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
Labels: Barbara

#4601 OKTA-676273 Update SCIM - determine if User already exists section
  packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
  packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
Labels: Graham

#4608 OKTA-366428 Update Postman collections topic
  packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
Labels: Barbara

#4543 OKTA-672599 - Add error example to Token Hook reference
  packages/@okta/vuepress-site/docs/reference/token-hook/index.md
Labels: Barbara

#4603 Add guide for SCIM with entitlements
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/scim-with-entitlements/index.md
  packages/@okta/vuepress-site/docs/guides/scim-with-entitlements/main/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Barbara, Susan

#4615 adding request example
  packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
Labels: Graham

#4616 updating left nav to match guide name
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Graham

#4612 OKTA-620025 Refresh basic sign in with widget guide
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-widget-dotnet-basic-sign-in-flow-diagram.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-widget-go-basic-sign-in-flow-diagram.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-widget-java-basic-sign-in-flow-diagram.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-widget-nodejs-basic-sign-in-flow-diagram.png
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/pwdoptionalusecase.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/pwdoptionalusecase.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/pwdoptionalusecase.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/aspnet/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/aspnet/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/aspnet/pwdoptionalusecase.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/aspnet/samplecode.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/aspnet/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/aspnet/whatyouneed.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/go/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/go/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/go/samplecode.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/go/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/go/whatyouneed.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/java/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/java/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/java/pwdoptionalusecase.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/java/samplecode.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/java/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/java/whatyouneed.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/nodejs/configureyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/nodejs/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/nodejs/pwdoptionalusecase.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/nodejs/samplecode.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/nodejs/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/nodejs/whatyouneed.md
Labels: docs update

#4619 adding private_key_jwt as an example
  packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
Labels: Barbara

#4618 OKTA-686715 Clean up figma diagrams
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-go-use-case-email-code-confirm-page.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-go-use-case-email-verify-page.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-use-case-pwd-recovery-screenshot-challenge-nodejs.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-use-case-sign-in-pwd-email-screen-verify-java.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-use-case-sign-in-pwd-email-screen-verify-nodejs.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-use-case-sign-in-pwd-email-screen-verify.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-sdk-use-case-swift-register-1.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-widget-golang-sample-app-idp-sign-in-page.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-widget-sample-app-signin.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-widget-use-case-load-java.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-widget-use-case-load-nodejs.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-widget-use-case-load.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-widget-use-case-sign-in-screen-java.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-widget-use-case-social-sign-in-screen-java.png
  packages/@okta/vuepress-site/.vuepress/public/img/oie-embedded-sdk/oie-embedded-widget-use-case-social-sign-in-screen.png
  packages/@okta/vuepress-site/.vuepress/public/img/wireframes/widget-sign-in-form-username-only-sign-up-forgot-your-password-facebook-links.png
  packages/@okta/vuepress-site/.vuepress/public/img/wireframes/widget-sign-in-form-username-only-sign-up-forgot-your-password-links.png
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/aspnet/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/go/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/java/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/nodejs/integrationsteps.md
Labels: docs update, Graham

#4592 OKTA-603865 Update Postman instructions with OAuth
  packages/@okta/vuepress-site/code/rest/index.md
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/monitor/index.md
  packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-user-scoped-account-management/main/index.md
  packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
  packages/@okta/vuepress-site/docs/guides/mfa/main/index.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-bulk/main/index.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-password-hooks/main/index.md
  packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/main/index.md
  packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/authn/index.md
  packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
  packages/@okta/vuepress-site/docs/reference/rest/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Graham

#4620 Rn entry 2024.01.2
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#3864 CSP for custom domains
  packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
Labels: docs release, final review complete, Graham

#4610 OKTA-676888 - Add granular authenticator control
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
Labels: docs release, Barbara
