Repository okta/okta-developer-docs, pull requests merged in 2024-03, with the labels that each got.

#4689 Update Telephony Hooks Ref
  packages/@okta/vuepress-site/docs/reference/telephony-hook/index.md
Labels: Graham

#4690 OKTA-702581 Updates to OIN Wizard backward compatibility section
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/backward-compatible-eg.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/backward-compatible-eg.md
Labels: Graham

#4692 Update Telephony Hook Guide
  packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
Labels: docs release, Susan

#4693 SIW3 Odyssey updates
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-border-space-after.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-border-space-before.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-color-after.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-color-before.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-color-text-after.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-color-text-border-after.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-text-after.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-text-before.png
  packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
Labels: docs release, Graham

#4688 Policy API: Add mappings links object
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
Labels: docs release, Graham

#4681 OKTA-688752 App provisioning connection with Okta APIs
  packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/index.md
  packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Graham

#4676 OKTA-694170 OAUTH2-use-external-key-for-org-as-access-token
  packages/@okta/vuepress-site/docs/concepts/auth-servers/index.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/index.md
Labels: docs release, Graham

#4680 [OKTA-702250] Feature Lifecycle Management page
  packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md
Labels: Susan, Graham

#4696 Release 2024.03.0
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-border-space-after.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-border-space-before.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-color-after.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-color-before.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-color-text-after.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-color-text-border-after.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-text-after.png
  packages/@okta/vuepress-site/.vuepress/public/img/siw-gen3/siw3-text-before.png
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
  packages/@okta/vuepress-site/docs/concepts/auth-servers/index.md
  packages/@okta/vuepress-site/docs/guides/add-private-app/main/openidconnect/settings.md
  packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/index.md
  packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md
  packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/grant-name.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/setup-app.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/interactioncode/configuration.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/setup-app.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/setup-app.md
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
  packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
  packages/@okta/vuepress-site/docs/guides/set-up-token-exchange/main/index.md
  packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#4700 Removed repeated Release Note for March monthly
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
Labels: Graham

#4701 Add links to API
  packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
Labels: Barbara

#4702 URL update
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#4704 Telephony Guide Round 3
  packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
Labels: Barbara

#4706 OKTA-703301 - Apps API update: add note for PUT /apps
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Labels: Graham

#4707 AMR claims and okta-to-okta orgs
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appatidp.md
  packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
  packages/@okta/vuepress-theme-prose/global-components/AMROktatoOkta.vue
Labels: Graham

#4713 Update links to redocly
  packages/@okta/vuepress-theme-prose/components/SidebarItem.vue
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Graham

#4715 OKTA-703301 Update property ordering in PUT apps API note
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Labels: Graham

#4716 OKTA-706467 Update References TOC to have external links for net-new APIs
  packages/@okta/vuepress-site/docs/reference/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#4712 Release 2024.03.1
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#4710 [OKTA-506563] widget
  packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md
  packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md
  packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/interactioncode/use-flow.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-oie/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/aspnet/runwidgetapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/nodejs/runsdkapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/nodejs/runwidgetapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/aspnet/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/go/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/java/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/nodejs/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/nodejs/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/summaryofsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/java/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/load-app.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
Labels: Susan

#4724 Third-party cookies: update link in D.O.C.
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/nutrition.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/overview.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sessions-api/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/users/index.md
Labels: Barbara

#4723 widget edits across the repo and the repercussions of that
  packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md
  packages/@okta/vuepress-site/docs/guides/device-context/main/aspnet/relatedusecases.md
  packages/@okta/vuepress-site/docs/guides/device-context/main/nodeexpress/relatedusecases.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/android/runsdkapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/aspnet/runsdkapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/ios/runsdkapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/java/runsdkapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/java/runwidgetapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/nodejs/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/aspnet/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/java/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/nodejs/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/android/auth.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/java/auth.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/see-also.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/see-also.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/see-also.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/see-also.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/see-also.md
Labels: Graham

#4726 Roles API: Clarifies credentials access
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
  packages/@okta/vuepress-site/docs/reference/api/roles/index.md
Labels: Barbara

#4714 [OKTA-705854] Policies doc upate
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Labels: Barbara

#4728 OKTA-710941 - Update SCIM test plan for OIN SCIM integration testing doc
  packages/@okta/vuepress-site/.vuepress/public/standards/SCIM/SCIMFiles/okta-scim-test-plan-v2.xlsx
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-test/main/index.md
Labels: Graham

#4731 [OKTA-707143] Release Lifecycle update
  packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md
Labels: Graham

#4732 [OKTA-707143] Part 2, additional fixes
  packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Graham

#4730 Remove DAC project references from the multi-tenant solutions document
  packages/@okta/vuepress-site/docs/concepts/multi-tenancy/index.md
Labels: Graham

#4733 Update to DNSSec note
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
Labels: Graham

#4736 Custom domain: DNSSec note update
  packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
Labels: Barbara

#4734 OKTA-707879 2024.03.2 RN entries
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#4741 OKTA-707879 2024.03.2 release notes
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara
