Repository okta/okta-developer-docs, pull requests merged in 2024-09, with the labels that each got.

#5049 OKTA-794271 Acrolinx edits for Work with Okta Session cookies
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sessions-api/main/index.md
  packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
Labels: Barbara

#5053 OKTA-744070 Reference banner update
  packages/@okta/vuepress-site/docs/reference/index.md
Labels: Susan

#5033 OKTA-752881 Org creator concept
  packages/@okta/vuepress-site/.vuepress/public/img/concepts/OrgCreatorFeaturePush.png
  packages/@okta/vuepress-site/docs/concepts/org-creator/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Barbara, Graham

#5025 OKTA-790239 deprecate Apps API components
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Labels: Barbara

#5036 Postman instructions update
  packages/@okta/vuepress-site/.vuepress/public/img/postman/postman_eye_icon_button.jpg
  packages/@okta/vuepress-site/.vuepress/public/img/postman/postman_eye_icon_button.png
  packages/@okta/vuepress-site/docs/reference/rest/index.md
Labels: Susan

#5046 [OKTA-794136] Users deprecation
  packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
  packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-okta-email/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/flow-diagram.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/flow-diagram.md
  packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/flow-diagram.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-password-hooks/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-new-user-activation/main/index.md
  packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/aspnet/allcontent.md
  packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/java/allcontent.md
  packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/nodeexpress/allcontent.md
  packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
  packages/@okta/vuepress-site/docs/guides/revoke-tokens/main/index.md
  packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/authn/index.md
  packages/@okta/vuepress-site/docs/reference/api/groups/index.md
  packages/@okta/vuepress-site/docs/reference/api/roles/index.md
  packages/@okta/vuepress-site/docs/reference/api/user-types/index.md
  packages/@okta/vuepress-site/docs/reference/api/users/index.md
  packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
  packages/@okta/vuepress-site/docs/reference/user-query/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
Labels: Barbara

#5057 Updated with required admin scopes
  packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md
Labels: Graham

#5059 Fixed postman links
  packages/@okta/vuepress-site/docs/reference/api/groups/index.md
  packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md
  packages/@okta/vuepress-site/docs/reference/api/users/index.md
Labels: Susan

#5061 OKTA-803560 Fix broken links for 2024.09.11
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Labels: Barbara

#5064 Small edit to banner message
  packages/@okta/vuepress-site/docs/reference/index.md
Labels: Barbara

#5063 OKTA-744019 RN entries for 2024.09.0
  packages/@okta/vuepress-site/.vuepress/public/img/homepage/APIDocs-menu.png
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#5065 OKTA-744019 - 2024.09.0 Release Notes
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/.vuepress/public/img/homepage/APIDocs-menu.png
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#5066 OKTA-755340 Deprecate Org API sections on VuePress
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/brands/index.md
  packages/@okta/vuepress-site/docs/reference/api/org/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022/index.md
Labels: Barbara

#5067 [Okta 751156] Acrolinx
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/aspnet/introspectendpointrequest.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/aspnet/refreshendpointrequest.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/go/introspectendpointrequest.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/go/refreshendpointrequest.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/ios/refreshusingthesdk.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/java/introspectendpointrequest.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/java/refreshendpointrequest.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/nodeexpress/introspectendpointrequest.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/nodeexpress/refreshusingthesdk.md
Labels: Graham

#5062 OKTA-794552 Acroedits - Sign in to SPA with AuthJs
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/basic-sign-in.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/download-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/intro.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/next-steps.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/see-also.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/basic-sign-in.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/download-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/intro.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/next-steps.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/see-also.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/basic-sign-in.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/download-sample.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/intro.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/next-steps.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/nutrition.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/see-also.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/sign-in-form.md
Labels: Barbara

#5071 OKTA-805824 Fix Client Role Assignment broken link in Apps API
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Labels: Barbara

#5060 Initial commit
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-configure-device-signin-standards/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-configure-device-signin-standards/main/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-organize-configuration/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-organize-configuration/main/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-syntax-tips/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-syntax-tips/main/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5072 OKTA-803971 - Move hook best practice to Guides
  .wokeignore
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/hooks-best-practices/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5073 Remove social idp buttons on signup
  packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
Labels: Susan

#5083 Fixed release note header
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
Labels: Barbara

#5081 deprecate token inline hook reference on vuepress
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
  packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
  packages/@okta/vuepress-site/docs/reference/token-hook/index.md
  packages/@okta/vuepress-site/docs/release-notes/2019/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5070 OKTA-743108 Deprecate Release lifecycle page
  packages/@okta/vuepress-site/code/library-versions/index.md
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/okta-organizations/index.md
  packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
  packages/@okta/vuepress-theme-prose/global-components/ApiLifecycle.vue
Labels: Barbara

#5077 OKTA-727513 - Deprecate Event Hooks Mgmt API on VuePress
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/event-hook-hookdeck/main/index.md
  packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md
  packages/@okta/vuepress-site/docs/release-notes/2019/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5088 Trusted Origins API deprecation
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
  packages/@okta/vuepress-site/docs/release-notes/2020/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#5090 OKTA-804951 Clarity for "Redirect vs embedded"
  packages/@okta/vuepress-site/docs/concepts/redirect-vs-embedded/index.md
Labels: Barbara

#5091 Custom sign-in page: improve clarity score
  packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
Labels: Barbara

#5084 User Types API deprecation
  packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md
  packages/@okta/vuepress-site/docs/reference/api/archive-myaccount/index.md
  packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
  packages/@okta/vuepress-site/docs/reference/api/user-types/index.md
  packages/@okta/vuepress-site/docs/reference/api/users/index.md
  packages/@okta/vuepress-site/docs/release-notes/2019/index.md
  packages/@okta/vuepress-site/docs/release-notes/2020/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
  tests/cypress/integration/tree_nav_spec.js
Labels: Barbara

#5087 Roles API deprecation
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
  packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/roles/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Susan

#5080 [OKTA-802677] Updates to SCIM 2.0 with entitlements
  packages/@okta/vuepress-site/docs/guides/scim-with-entitlements/main/index.md
Labels: Susan

#5086 OKTA-806883 - Deprecate remaining hook apis from vuepress
  packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
  packages/@okta/vuepress-site/docs/guides/archive-registration-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/archive-registration-inline-hook/main/nodejs/get-submitted-credentials.md
  packages/@okta/vuepress-site/docs/guides/archive-registration-inline-hook/main/nodejs/send-response.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-password-hooks/main/index.md
  packages/@okta/vuepress-site/docs/guides/migrate-to-okta-prerequisites/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/nodejs/response-properties.md
  packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/apps/index.md
  packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
  packages/@okta/vuepress-site/docs/reference/api/users/index.md
  packages/@okta/vuepress-site/docs/reference/import-hook/index.md
  packages/@okta/vuepress-site/docs/reference/index.md
  packages/@okta/vuepress-site/docs/reference/password-hook/index.md
  packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
  packages/@okta/vuepress-site/docs/reference/saml-hook/index.md
  packages/@okta/vuepress-site/docs/reference/telephony-hook/index.md
  packages/@okta/vuepress-site/docs/reference/token-hook/index.md
  packages/@okta/vuepress-site/docs/release-notes/2019/index.md
  packages/@okta/vuepress-site/docs/release-notes/2020/index.md
  packages/@okta/vuepress-site/docs/release-notes/2021/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5093 OKTA-807904 - Deprecate Hook Keys API on VuePress
  packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/hook-keys/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2022/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5074 OKTA-710607 Deprecate SSO in OIN Manager
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/index.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#5096 Google authenticator guide: Acrolinx clarity score
  packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/aspnet/challengeintegrationsteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/aspnet/enrollmentintegrationsteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/java/challengeintegrationsteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/java/enrollmentintegrationsteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/nodeexpress/challengeintegrationsteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/nodeexpress/enrollmentintegrationsteps.md
Labels: Susan

#5092 OKTA-804418 Deprecate Apps API: update /apps API links to Redocly
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md
  packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md
  packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
  packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/sdksteps.md
  packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/sdksteps.md
  packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
  packages/@okta/vuepress-site/docs/guides/policy-simulation/main/index.md
  packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
  packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
  packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
  packages/@okta/vuepress-site/docs/guides/sharing-cert/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/main/index.md
  packages/@okta/vuepress-site/docs/guides/updating-saml-cert/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/reference/api/roles/index.md
  packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
  packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
  packages/@okta/vuepress-site/docs/release-notes/2016/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Susan

#5099 OKTA-809423 - Create system log query guide
  packages/@okta/vuepress-site/docs/reference/system-log-query/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#5101 OKTA-807236 - Remove rate limit content
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md
  packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
  packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
  packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
  packages/@okta/vuepress-site/docs/reference/rl-global-mgmt/index.md
  packages/@okta/vuepress-site/docs/reference/rl-global-other-endpoints/index.md
  packages/@okta/vuepress-site/docs/reference/rl-previous/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5085 OKTA-476264 Adding SIW variable
  packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
  packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
  packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md
  packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/siw.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/siw.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/go/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/java/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/nodejs/integrationsteps.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
Labels: Brent

#5104 OKTA-798706 ref landing page update
  packages/@okta/vuepress-site/docs/reference/index.md
Labels: Barbara

#5058 Deprecation VuePress Policies API
  packages/@okta/vuepress-site/conductor.yml
  packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md
  packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/guides/archive-configure-signon-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-mfa-enroll-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/policy-simulation/main/index.md
  packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/main/ios/enablesso.md
  packages/@okta/vuepress-site/docs/guides/step-up-authentication/main/index.md
  packages/@okta/vuepress-site/docs/reference/api/policy/index.md
  packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
  packages/@okta/vuepress-site/docs/reference/password-hook/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara
