Repository okta/okta-developer-docs, pull requests merged in 2024-11, with the labels that each got.

#5176 OKTA-809933 Remove guides/submit-sso-app files
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/index.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/openidconnect/protocol-name.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/openidconnect/see-also.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/openidconnect/submit.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/saml2/protocol-name.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/saml2/see-also.md
  packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/saml2/submit.md
Labels: Graham

#5172 Update VuePress SPA Guide
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/addconfigpkg.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/createproject.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/getuserinfo.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/loginredirect.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/redirectvalues.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/reqautheverything.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/reqauthspecific.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/specificlinks.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/testapp.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/useaccesstoken.md
Labels: Susan

#5165 OKTA-796859 SCIM update
  packages/@okta/vuepress-site/docs/concepts/scim/index.md
Labels: Susan

#5169 Multiple IDs API guide
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/multiple-identifiers/index.md
  packages/@okta/vuepress-site/docs/guides/multiple-identifiers/main/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Barbara

#5160 OKTA-809675 OIN Wizard - Navigate to Test integrations page
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: docs release, Barbara

#5180 Release 2024.11.0
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
  packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/multiple-identifiers/index.md
  packages/@okta/vuepress-site/docs/guides/multiple-identifiers/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/index.md
  packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/main/index.md
  packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/nodejs/enrollment-policy.md
  packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#5194 OKTA-826953 Add redocly links after redocly publish
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Graham

#5190 Acrolinx clarity score: mobile redirect guide
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/configmid.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/createproject.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/redirectvalues.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/samplecode.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/testapp.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/addconfigpkg.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/configmid.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/createproject.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/opensignin.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/refresh.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/samplecode.md
  packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/testapp.md
Labels: Barbara

#5200 Add post release bugs or features
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#5206 OKTA-832187 - Update copyright page to remove broken link
  packages/@okta/vuepress-site/copyright/index.md
Labels: Susan

#5202 OKTA-830415 Updates for migrated SCIM integrations
  packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: Barbara

#5209 OKTA-833857 - Removed link to Toolkit
  packages/@okta/vuepress-site/.vuepress/config.js
  packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md
Labels: Barbara

#5213 Ignores platform
  scripts/setup.sh
Labels: Barbara

#5214 Switching steps to use the UI to assign admin roles
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
Labels: Barbara
