Repository okta/okta-developer-docs, pull requests merged in 2025-02, with the labels that each got.

#5311 Update to false positives list
  falsepos.txt
Labels: Barbara

#5304 remove EA tag for Account Link SAML
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
Labels: docs release

#5299 Groups claim update for SAML
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/saml2/prep.md
Labels: docs release, Barbara

#5312 OKTA-850925 - Release Note Entry 2025.02.0
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Susan

#5313 OKTA-857932 - IGA Release Notes
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5315 Minor fix to links
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Barbara

#5316 Mock up of IGA Changelog
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
  packages/@okta/vuepress-site/docs/release-notes/archive/index.md
  packages/@okta/vuepress-site/docs/release-notes/archive/oig-changelog.md
  packages/@okta/vuepress-site/docs/release-notes/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5322 OKTA-866047 - Doc action RN removal
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Barbara

#5325 Release 2025.02.1
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Barbara

#5328 Revise URLs for IGA RNs
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
Labels: Susan

#5330 Update urls with absolute path
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
Labels: Susan
