Repository okta/okta-developer-docs, pull requests merged in 2025-07, with the labels that each got.

#5547 Add ACS URL validation
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md
Labels: Barbara

#5557 OKTA-971041 - Add Glitch deprecation note
  packages/@okta/vuepress-site/docs/guides/archive-registration-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
  packages/@okta/vuepress-site/docs/guides/dpop/main/index.md
  packages/@okta/vuepress-site/docs/guides/event-hook-filtering/main/index.md
  packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
  packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
  packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
  packages/@okta/vuepress-theme-prose/global-components/GlitchDeprecationNote.vue
Labels: Susan

#5561 Update SAML user profile properties
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md
Labels: Barbara

#5554 OKTA-946202 OAuth 2.0 token lifecycle concept for OCI
  packages/@okta/vuepress-site/docs/concepts/token-lifecycles/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#5518 OKTA-899867 - Add tag images to event types
  packages/@okta/vuepress-site/docs/reference/api/event-types/index.md
Labels: Barbara

#5536 OKTA-954434 Associated domains
  packages/@okta/vuepress-site/docs/guides/custom-well-known-uri/index.md
  packages/@okta/vuepress-site/docs/guides/custom-well-known-uri/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Susan

#5503 TAC authenticator
  packages/@okta/vuepress-site/docs/guides/authenticators-overview/main/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-tac-authenticator/index.md
  packages/@okta/vuepress-site/docs/guides/authenticators-tac-authenticator/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release

#5582 [2025.07.1 Release Notes]
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Barbara

#5590 Update description of default policy
  packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
Labels: Barbara

#5610 adding examples and removing ea tags
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
  packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
Labels: docs release
