Repository okta/okta-developer-docs, pull requests merged in 2025-04, with the labels that each got.

#5336 removed EA flag
  packages/@okta/vuepress-site/docs/guides/federated-claims/main/index.md
Labels: docs release

#5349 OKTA-838079 Org2Org provisioning enhancement updates
  packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
Labels: docs release, Brent

#5377 SIW (Gen2 and Gen3): Add description of new useSiwGen3 variable
  packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
Labels: docs release

#5382 Add RN entry to 2025.03.3
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Susan

#5385 Update integration variable limit increase
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: Barbara

#5386 OKTA-883116: Update Okta Browser Plugin version
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
Labels: Barbara

#5384 OKTA-904279 | DevDocs - Remove modal from developer.okta.com
  packages/@okta/vuepress-theme-prose/assets/css/components/_dialog.scss
  packages/@okta/vuepress-theme-prose/assets/css/prose.scss
  packages/@okta/vuepress-theme-prose/components/Dialog.vue
  packages/@okta/vuepress-theme-prose/components/Home.vue
Labels: Susan

#5387 OKTA-898112 - Release Note entry for 2025.04.1
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Barbara

#5392 OKTA-917092 Fix formatting in IGA RN blurb
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
Labels: Barbara

#5409 aj-OKTA-893383
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Labels: Susan
