Repository okta/okta-developer-docs, pull requests merged in 2025-05, with the labels that each got.

#5419 Phrasing update per feedback from Susan
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Labels: Barbara

#5418 Update sign in to SPA embedded SIW guide
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/load-app.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/basic-sign-in.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/load-app.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/load-app.md
Labels: Barbara

#5421 OKTA-926593: Add vuln ticket | Release 2025.04.3
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
Labels: Barbara

#5407 OKTA-913556: Express Configuration
  packages/@okta/vuepress-site/.vuepress/public/img/oin/ec_configure_SSO_with_OIDC.png
  packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/see-also.md
  packages/@okta/vuepress-site/docs/guides/enable-express-configuration/index.md
  packages/@okta/vuepress-site/docs/guides/enable-express-configuration/main/index.md
  packages/@okta/vuepress-site/docs/guides/express-configuration/index.md
  packages/@okta/vuepress-site/docs/guides/express-configuration/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/see-also.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Susan

#5410 SSF Transmitter SET JWT payload examples
  packages/@okta/vuepress-site/docs/reference/ssf-transmitter-sets/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Barbara

#5412 Identity verification vendor integration guide
  packages/@okta/vuepress-site/.vuepress/public/img/identity-verification/diagram-idv-integration.png
  packages/@okta/vuepress-site/docs/guides/add-id-verification-idp/main/index.md
  packages/@okta/vuepress-site/docs/guides/add-id-verification-idp/main/persona/idpaccount.md
  packages/@okta/vuepress-site/docs/guides/idv-integration/index.md
  packages/@okta/vuepress-site/docs/guides/idv-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: docs release, Barbara

#5423 ga updates
  packages/@okta/vuepress-site/docs/guides/configure-claims-sharing/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-claims-sharing/main/oktaoidc/wun.md
  packages/@okta/vuepress-site/docs/guides/configure-claims-sharing/main/oktasaml/wun.md
  packages/@okta/vuepress-site/docs/guides/configure-claims-sharing/main/thirdpartyoidc/wun.md
  packages/@okta/vuepress-site/docs/guides/configure-claims-sharing/main/thirdpartysaml/wun.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/load-app.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/basic-sign-in.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/load-app.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/create-app-integration.md
  packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/load-app.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
Labels: docs release

#5401 OKTA-913554 manager/assistant EL functions
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Labels: Barbara

#5432 OKTA-921857| Updated based on Support ticket - Remove dev org reference
  packages/@okta/vuepress-site/docs/guides/scim-with-entitlements/main/index.md
Labels: Barbara

#5433 Remove authorization from description
  packages/@okta/vuepress-site/docs/guides/idv-integration/main/index.md
Labels: Barbara

#5398 OKTA-857293 WebAuthn guide update
  packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/index.md
Labels: Barbara

#5416 OKTA-293664 - Clarify email rate limit docs
  packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
  packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
Labels: Barbara

#5415 OKTA-873736 - Adding content for banner
  packages/@okta/vuepress-theme-prose/components/Hero.vue
  packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
  packages/@okta/vuepress-theme-prose/layouts/Layout.vue
Labels: Barbara

#5403 OKTA-903113 - Minor updates to rate limit docs
  packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
  packages/@okta/vuepress-site/docs/reference/rl-global-mgmt/index.md
Labels: Barbara

#5439 Grace period for authenticator enrollment policies
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
Labels: docs release, Barbara

#5455 Gen2 to Gen3 SIW migration guide
  packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-widget-migration-gen3/index.md
  packages/@okta/vuepress-site/docs/guides/custom-widget-migration-gen3/main/index.md
  packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5451 OKTA-921202 - Updates to headers on rate limit tables
  packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
  packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
  packages/@okta/vuepress-site/docs/reference/rl-global-mgmt/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5457 OKTA-887860: Update Integrator Free Plan changes in OIN docs
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: Barbara

#5458 OKTA-940225 - Update broken link
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/loginredirect.md
Labels: Barbara

#5461 OKTA-940225 - Update URL to official rxjs documentation
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/loginredirect.md
Labels: Barbara

#5441 OKTA-936226 Email expression
  .github/acrolinx/global-config.edn
  packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
Labels: docs release, Susan
