Repository okta/okta-developer-docs, pull requests merged in 2025-01, with the labels that each got.

#5265 OKTA-818824 - Weekly release notes
  packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md
  packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
  packages/@okta/vuepress-site/docs/guides/federated-claims/index.md
  packages/@okta/vuepress-site/docs/guides/federated-claims/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5263 OKTA-848162 - React SPA guide updates
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/addconfigpkg.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/configmid.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/createproject.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/getuserinfo.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/handlecallback.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/loginredirect.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/redirectvalues.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/reqauthspecific.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/specificlinks.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/testapp.md
  packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/useaccesstoken.md
Labels: Barbara

#5259 Device assurance policy: update policies concept doc
  packages/@okta/vuepress-site/docs/concepts/policies/index.md
Labels: Barbara

#5272 Rn entry 2025.01.0
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5269 [OKTA-849174] group.source.id
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
Labels: docs release, Susan

#5268 KMSI GA
  packages/@okta/vuepress-site/docs/guides/keep-me-signed-in/main/index.md
Labels: docs release, Barbara

#5262 OKTA-845931 Additional use cases in OIN Wizard
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: docs release, Barbara

#5274 RNs - fix broken internal link
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Barbara

#5271 Client secret rotation and key mgmt - typo fix
  packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md
Labels: Susan

#5275 OKTA-851282 Update test account lifespan note for OIN
  packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
Labels: Barbara

#5278 Release 2025.01.1
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Susan

#5283 Update Style the Sign-In Widget (third generation) Guide
  packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
Labels: Susan

#5281 OKTA-852686 - alias fixies
  packages/@okta/vuepress-site/archive/php/sign-into-web-app-redirect/index.md
  packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/index.md
  packages/@okta/vuepress-site/docs/guides/terraform-manage-end-user-experience/main/index.md
  packages/@okta/vuepress-site/docs/reference/architecture-center/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2023/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Labels: Barbara

#5285 OKTA-850793 lowercasing objects
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
  packages/@okta/vuepress-site/docs/reference/user-query/index.md
Labels: Susan

#5255 Device assurance policies guide
  packages/@okta/vuepress-site/docs/guides/device-assurance-policies/index.md
  packages/@okta/vuepress-site/docs/guides/device-assurance-policies/main/index.md
  packages/@okta/vuepress-site/docs/guides/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Barbara

#5279 OKTA-809892 Add API service integration in OIN Manager docs
  packages/@okta/vuepress-site/.vuepress/public/img/icons/odyssey/APIs.svg
  packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/apiservice/protocol-name.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/apiservice/see-also.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/apiservice/submit.md
  packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
  packages/@okta/vuepress-theme-prose/assets/css/okta/icons/classes.scss
  packages/@okta/vuepress-theme-prose/util/frameworks.js
Labels: Barbara

#5290 OKTA-852236: Updated overview
  packages/@okta/vuepress-site/docs/guides/oin-sso-overview/index.md
Labels: Barbara

#5291 OKTA-755287 Update to any Okta org for Create an API token topic
  packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
Labels: Barbara

#5288 AuthN API: Fixes factors typo
  packages/@okta/vuepress-site/docs/reference/api/authn/index.md
Labels: Barbara

#5292 Device Assurance Policy API guide: typo
  packages/@okta/vuepress-site/docs/guides/device-assurance-policies/main/index.md
Labels: Barbara

#5298 [OKTA-856135] Archive
  packages/@okta/vuepress-site/docs/release-notes/archive/index.md
  packages/@okta/vuepress-site/docs/release-notes/index.md
  packages/@okta/vuepress-theme-prose/const/navbar.const.js
Labels: Susan

#5303 small tweaks
  packages/@okta/vuepress-site/docs/guides/configure-claims-sharing/main/index.md
  packages/@okta/vuepress-site/docs/guides/configure-claims-sharing/main/oktaoidc/idpauthclaimssharing.md
Labels: Barbara

#5305 OKTA-859160 Copyright year
  packages/@okta/vuepress-site/copyright/index.md
Labels: Susan
