Repository okta/okta-developer-docs, pull requests merged in 2025-06, with the labels that each got.

#5424 OKTA-746990 - Burst rate limit updates
  packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
  packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
Labels: Susan

#5483 OKTA-899035 Release 2025.05.1 IGA - Doc Action
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
Labels: Susan

#5501 Additional editorial fixes
  packages/@okta/vuepress-site/cla/index.md
  packages/@okta/vuepress-site/terms/index.md
Labels: Barbara

#5508 OKTA-954411: Update request body examples
  packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md
Labels: Susan

#5525 [OKTA-962954] Expression Language doc updates (user.getGroups)
  packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
  packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Labels: Susan

#5526 2025.06.0 RN hotfix
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Susan

#5524 OKTA-958137 - Add info on Okta Integration IdP for Org2Org guide
  packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
Labels: docs release, Susan

#5533 Remove EA tag for IDV feature
  packages/@okta/vuepress-site/docs/guides/idv-integration/main/index.md
Labels: Susan

#5531 OKTA-941801 - Release 2025.06.2
  packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Susan
