Repository okta/okta-developer-docs, pull requests merged in 2025-03, with the labels that each got.

#5348 OKTA-885956 Set up an app provisioning connection - updates
  packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md
Labels: Susan

#5354 OKTA-887171 Public client app admins org setting - update placement
  packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
Labels: Susan

#5345 Remove note about GSP default rule
  packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
Labels: docs release, Susan

#5355 OKTA-887213 - Update 3rd-party licenses
  packages/@okta/vuepress-site/3rd_party_notices/Okta_Auth_SDK/index.md
  packages/@okta/vuepress-site/3rd_party_notices/Okta_Sign-In_Widget/index.md
Labels: Susan

#5350 OKTA-814631 - Rate Limits Best Practices - Update request exception
  packages/@okta/vuepress-site/docs/reference/rl-best-practices/index.md
Labels: Susan

#5356 OKTA-869706: Release 2025.03.0
  packages/@okta/vuepress-site/.vuepress/public/docs/okta-event-types.csv
  packages/@okta/vuepress-site/data/error-codes.json
  packages/@okta/vuepress-site/data/event-types.json
  packages/@okta/vuepress-site/data/oauth2-error-codes.json
  packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
  yarn.lock
Labels: Susan

#5361 fix jti and add text around replay attack
  packages/@okta/vuepress-site/docs/guides/dpop/main/index.md
Labels: Barbara

#5362 Explain auth code behavior with groups claim and ID tokens
  packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md
Labels: Barbara

#5365 Release 2025.03.1
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Barbara

#5367 Remove OKTA-856262 entry from Release Notes
  packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
  packages/@okta/vuepress-site/docs/release-notes/2025/index.md
Labels: Susan

#5366 OKTA-877160 Telephony guide update
  packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
Labels: Barbara
